application:
  version: ${version}

server:
  port: 8080
  servlet:
    contextPath: /checkit-server

keycloak:
  realm: YourRealm
  clientId: CheckIt-server
  authUrl: http://localhost/auth
  realmKey: YourKey
  secret: YourSecret
  adminAPI:
    username: admincheckit
    password: pass

repository:
  url: http://localhost/repo
  driver: cz.cvut.kbss.ontodriver.rdf4j.Rdf4jDataSource
  language: cs
  userIdPrefix: https://slovník.gov.cz/uživatel/

