application:
  version: ${version}
  publicationContext:
    pageSize: 15
  notification:
    pageSize: 15
  comment:
    rejectionMinimalContentLength: 10


logging:
  level:
    root: info

server:
  error:
    include-message: always
  port: 8080
  servlet:
    contextPath: /checkit-server

keycloak:
  realm: your-realm
  clientId: client-checkit-server
  url: http://keyclaok:8080/
  realmKey: YourRealmKeyThatIsVeryLongAndUsuallyStartsLikeThisMIIBIjANB
  secret: YourSecret-Looking-Like-This-858d5e62a5e5
  apiAdmin:
    username: admincheckit
    password: pass

repository:
  url: http://localhost:7200/repositories/myRepo
  driver: cz.cvut.kbss.ontodriver.rdf4j.Rdf4jDataSource
  language: cs
  user:
    idPrefix: https://slovník.gov.cz/uživatel/
    context: https://slovník.gov.cz/uživatel
  gestoringRequest:
    context: https://slovník.gov.cz/datový/popis-zmen/pozadavky-na-gestorovani
  comment:
    context: https://slovník.gov.cz/datový/popis-zmen/komentare
  notification:
    context: https://slovník.gov.cz/datový/popis-zmen/notifikace

