name: Test application

on:
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: al-checkit-server
  USERNAME: ${{ github.actor }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Gradle 8.0.1
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: gradle clean build -x test -x checkstyleMain -x checkstyleTest

      - name: Checkstyle
        run: gradle checkstyleMain checkstyleTest

      - name: Test
        run: gradle test
